### PR TITLE
Track pycharm run configuration in git repository.

### PR DESCRIPTION
**Pull request by lmarini**

### CODE REVIEW

**Comment by ddey2** [comment]
@lmarini Can you help me with the steps how to test this?

**Comment by longshuicy** [comment]
How to use/import those xml?

**Review by longshuicy — APPROVED** [review]

**Comment by lmarini** [comment]
Not sure how they get imported. I was hoping they would just appear? :)

**Review by ddey2 — APPROVED** [review]
Checked out branch, closed IDE and the configs appeared.

**Pull request merged**
