### PR TITLE
Fix refresh token issue when using password flow

### PR DESCRIPTION
**Pull request by GalMunGral**
- Related:  ncsa/idot-pma#173
- `POST /login` and `POST /auth/login` have the exact same logic. @longshuicy suggested deprecating the `POST /login` endpoint.
- Applied the same logic for refresh tokens as used in the authorization code flow (`GET /auth`) so that access tokens obtained through the password flow (`POST /auth/login`) can also be refreshed by `GET /auth/refresh_token`.

### CODE REVIEW

**Review by longshuicy — CHANGES_REQUESTED** [review]
Code looks good and tested. 
One thing I noticed is the "deprecated" not seems to work? I can still POST to the /api/v2/login endpoint with no issue. And i didn't see any notification either.
Could you look into that? if it's not straightforward, maybe we can just delete this endpoint. But we might be careful, a quick search I found there are some scripts (in the scripts folder) still uses this endpoint.

**Comment by longshuicy** [comment]
After we discussed, could you try below:

1. Make a utility function of that tokenDB logic. You can put it in `backend/app/routers/utils.py`.
2. Then revert the deprecate. We might want to keep both endpoints. (so you don't need to worry about making deprecating work)
3. Put the logic in /auth/login and /login

**Comment by max-zilla** [comment]
@longshuicy i will take a look at this also but it's ready for another look, thanks.

**Review by longshuicy — APPROVED** [review]
Code looks good and functionality works. Approve.

**Pull request merged**
