### PR TITLE
Root directory cleanup

### PR DESCRIPTION
**Pull request by lmarini**
- Moved docker compose files to root and fixed deployments for both dev and prod
- Prod instance now runs all services behind traefik on port 80 at different paths. Frontend is at `/`. Backend at `api`. Keycloak at `/keycloak`.
- Keycloak now runs under `/keycloak` instead of `/auth` for both prod and dev.
- Fixed github workflows. Added backend github action.
- Updated README.md

### CODE REVIEW

**Comment by tcnichol** [comment]
This might be minor, but I notice that when I uploaded a file, the spaces in the file name were replaced with the %20
clowder2_files


Also, I am getting an error when I try to delete the file (back end)
`INFO:     127.0.0.1:50292 - "DELETE /api/v2/files/62a0c05f90768e0d94ffc520 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/helium/ncsa/clowder2/backend/app/routers/files.py", line 119, in delete_file
    removed_vers = await db["file_versions"].delete({"file_id": ObjectId(file_id)})
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/motor/core.py", line 771, in __call__
    raise TypeError(
TypeError: MotorCollection object is not callable. If you meant to call the 'file_versions.delete' method on a MotorCollection object it is failing because no such method exists.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/helium/ncsa/clowder2/backend/app/routers/files.py", line 119, in delete_file
    removed_vers = await db["file_versions"].delete({"file_id": ObjectId(file_id)})
  File "/opt/anaconda3/envs/clowder/lib/python3.10/site-packages/motor/core.py", line 771, in __call__
    raise TypeError(
TypeError: MotorCollection object is not callable. If you meant to call the 'file_versions.delete' method on a MotorCollection object it is failing because no such method exists.`

**Comment by lmarini** [comment]
Thanks @tcnichol . These are not directly related to this PR and this PR should change that code (besides linting). If you could bring up the project and most things worked can you approve? Did you try the standalone docker compose or the development one (running backend and frontend on your host?). 

Can you create the issues/improvements you mention in the comment as standalone so we can take a look at them separate? Thank you.

**Comment by tcnichol** [comment]
I'm going to mark approved - any issues exist in the main branch and are separate issues.

**Review by tcnichol — APPROVED** [review]
Marking approved. All changes look fine. Any issues I found in testing are separate issues.

**Pull request merged**
