### PR TITLE
update breadcrumb

### PR DESCRIPTION
**Pull request by longshuicy**
@tcnichol here are a few minor things i changed towards your branch. Let me know if they look ok? Thanks!

### CODE REVIEW

**Comment by tcnichol** [comment]
It looks like the download button and menu for file are moved on this branch. This seems to happen even with fullscreen.
download_button

**Comment by longshuicy** [comment]
> It looks like the download button and menu for file are moved on this branch. This seems to happen even with fullscreen. download_button

Turns out the file layout is different than dataset layout. I match them now, please check. Thanks!

**Comment by tcnichol** [comment]
I reran tests this looks good so I can approve when they have passed.

**Review by tcnichol — APPROVED** [review]
The download button is back in the right spot for File and tests are now passing, marking approved.

**Pull request merged**
