### PR TITLE
visualization_config_id now in the visualization_data object

### PR DESCRIPTION
**Pull request by tcnichol**
I think this fixes the issue, though was not sure if routes needed to be changed or if that would all happen in previews/extractors or pyclowder.

### CODE REVIEW

**Review by max-zilla — CHANGES_REQUESTED** [review]
I think this should also include the functionality that hitting DELETE endpoint for visualization_config should delete any vis_data associated with that config.

**Comment by tcnichol** [comment]
> I think this should also include the functionality that hitting DELETE endpoint for visualization_config should delete any vis_data associated with that config.

This should be the case now both ways.

**Review by ddey2 — APPROVED** [review]
looks good.

**Review by longshuicy — APPROVED** [review]
Works well. 
I only have a question about vis config attaching the whole vis data model as its output. 
Would it be too much of the payload? 
@lmarini @max-zilla thoughts?

**Review by max-zilla — APPROVED** [review]

**Pull request merged**
