### PR TITLE
961 add footer for frontend pages

### PR DESCRIPTION
**Pull request by longshuicy**
Implemented a footer.
- When there is long page, this footer will sink to the bottom
- When there is a short page, this footer stick to the bottom of the view part
- When side bar opens and collapses, this footer shrink/expand accordingly

To test, please try various pages and see how it looks.

Some screenshots. 
Education skin ever baby white page later
Pasted Graphic 84
image

### CODE REVIEW

**Review by ddey2 — COMMENTED** [review]
It looks good. There is no footer for the public page. Is that intended?

**Review by lmarini — APPROVED** [review]
Looks great. Made minor modifications to links and text.

**Comment by longshuicy** [comment]
> It looks good. There is no footer for the public page. Is that intended?

sorry just added that to public page too

**Review by ddey2 — APPROVED** [review]
looks good

**Pull request merged**
