### PR TITLE
615 copy link to visualization bytes

### PR DESCRIPTION
**Pull request by longshuicy**
On backend:
1. run the test_visualization.py

On frontend:
1. running image previewer v2 extractor
2. upload image files then generate visualization bytes
3. on the visualization card click share and copy the link
4. paste the link in an incognito browser to see if you can download the image without username and password

On production it also worked:
Try this link see if you can download https://minio-api.clowder2.software-dev.ncsa.cloud/clowder/64d3f51ca7f29b3d17c17b2c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=clowder%2F20230809%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230809T204128Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=4956fdf63b4fadd8b6c804694c5584092d6b94f6ff1916d1dfd92c927958c1db

Here are some screenshots:
image
image

### CODE REVIEW

**Comment by longshuicy** [comment]
Need to test with production docker-compose and deployment too

**Comment by tcnichol** [comment]
Is there any way to make sure the file extension is in the downloaded file? Mine didn't have it but when I made it .png it worked and was visible.

**Comment by longshuicy** [comment]
> Is there any way to make sure the file extension is in the downloaded file? Mine didn't have it but when I made it .png it worked and was visible.

This may related to how those visualization are stored in the minio... i think we store them without file extension hence when download they don't have any file extension

**Comment by longshuicy** [comment]
closing this since #655 has this

**Pull request closed without merging**
