### PR TITLE
helmchart to deploy clowder2 in kubernetes

### PR DESCRIPTION
**Pull request by robkooper**
This is an initial helm chart

### CODE REVIEW

**Comment by robkooper** [comment]
this is still work in progress, however we got it to work on local machine with docker/kubernetes

- [ ] need to import keycloak.json realm @longshuicy  is minifying it
- [ ] need to import theme into keycloak container
- [ ] need to setup redirect in keycloak.json file when importing
- [ ] need to fix hardcode redirect in backend deployment

**Comment by robkooper** [comment]
this fixes #112

**Comment by longshuicy** [comment]
for minio i see these hardcoded in `config.py`?
```
 MINIO_SERVER_URL: str = "localhost:9000"
    MINIO_BUCKET_NAME: str = "clowder"
    MINIO_ACCESS_KEY: str = "minioadmin"
    MINIO_SECRET_KEY: str = "minioadmin"
    MINIO_UPLOAD_CHUNK_SIZE: int = 10 * 1024 * 1024
    ```

For elasticsearch I see those:
```
# Elasticsearch local config
    elasticsearch_url = "http://localhost:9200"
    elasticsearch_no_of_shards = 5
    elasticsearch_no_of_replicas = 5
    ```

**Review by longshuicy — APPROVED** [review]

**Comment by lmarini** [comment]
Is this ready to go?

**Comment by robkooper** [comment]
Did the hardcoded values in minio get fixed? One option is to merge for now and create some issues for the left over pieces.

**Comment by longshuicy** [comment]
I created issues to capture the things left to do https://github.com/clowder-framework/clowder2/issues/200
Maybe a few are duplicated even but we'll see

**Pull request merged**
