### PR TITLE
Removing version column from File entry view

### PR DESCRIPTION
**Pull request by ddey2**
Current file entry should look like this:
Screenshot 2024-06-20 at 11 48 54 AM

### CODE REVIEW

**Review by tcnichol — APPROVED** [review]
This looks fine I'm marking approved.

**Review by longshuicy — COMMENTED** [review]
Could you match folder to match the column number 
image

**Comment by ddey2** [comment]
> Could you match folder to match the column number image

done. Good catch, thanks!

**Review by longshuicy — APPROVED** [review]
Works as expected now.

**Pull request merged**
