### PR TITLE
844 toggle on and off of the extractor livelihood

### PR DESCRIPTION
**Pull request by longshuicy**
Backend:
- Use aggregated query to calculate "alive" at the whole collection level; then apply different filters

Frontend
- Add a switch to toggle on/off view only alive extractors

image

### CODE REVIEW

**Review by ddey2 — CHANGES_REQUESTED** [review]
The code looks okay but I am not able to get it working. 
@longshuicy I am testing the code by setting the heartbeat interval to 20 secs and stopping the extractor. I am still finding the extractor to be alive even after several minutes. Is there something I am missing?
Screenshot 2024-01-16 at 2 55 08 PM
Screenshot 2024-01-16 at 2 54 53 PM
Screenshot 2024-01-16 at 2 54 58 PM

**Comment by longshuicy** [comment]
> The code looks okay but I am not able to get it working. @longshuicy I am testing the code by setting the heartbeat interval to 20 secs and stopping the extractor. I am still finding the extractor to be alive even after several minutes. Is there something I am missing? Screenshot 2024-01-16 at 2 55 08 PM Screenshot 2024-01-16 at 2 54 53 PM Screenshot 2024-01-16 at 2 54 58 PM

This is the "default" fallback. Maybe just don't change anything and wait for 5 minutes see if it died. If not I can revisit and see if there is a bug in my code. Thank you!

**Comment by tcnichol** [comment]
I noticed the same thing as @ddey2 but with 5 minutes. If I left the tab and went back the dot was red though.

**Comment by ddey2** [comment]
I think I am having issues running extractors. Clowder isn't getting any messages from the extractor. That's the reason why I am probably not seeing the red dots even after 5 mins. 

@tcnichol If you've tested the code, feel free to approve and merge it.

**Comment by lmarini** [comment]
@longshuicy @ddey2 @tcnichol It worked for me. I just had to refresh the page to see the red dot.

**Review by lmarini — APPROVED** [review]

**Pull request merged**
