### PR TITLE
904 allow folder renaming

### PR DESCRIPTION
**Pull request by longshuicy**
Backend change:
- Added PATCH /datasets/{datasetId}/folders/{folderID} endpoint
- Added GET /datasets/{datasetId}/folders/{folderID} endpoint --> but not being used in the frontend yet
- Pytest added

Frontend:
- Rename folder capability
- Authwrapper wrap around the folder menu to only allow "owner", "editor" and "admin" to delete or rename folder

Pasted Graphic 4
Rename Folder
Pasted Graphic 5

-----

To test:

1. Run the pytest
2. Create a few folders and nested folders
3. Rename, delete, add files see if everything works
4. Switch to public view to make sure "folder menu" disappeard

### CODE REVIEW

**Comment by tcnichol** [comment]
Something I noticed.

I have 2 folders in a dataset. I go to rename the first one.

After that, if I click 'rename' on the second one, it shows the name of the first one and not the name of the folder. 

Uploaded a video.

https://github.com/clowder-framework/clowder2/assets/40038535/61cf909f-27b7-4b54-947d-41252906e530

**Comment by longshuicy** [comment]
> Something I noticed.
> 
> I have 2 folders in a dataset. I go to rename the first one.
> 
> After that, if I click 'rename' on the second one, it shows the name of the first one and not the name of the folder.
> 
> Uploaded a video.
> 
>  Screen.Recording.2024-02-08.at.9.42.05.AM.mov

Good catch I'll try fixing it

**Comment by tcnichol** [comment]
> @longshuicy I can't see the 'Rename' option.
> 
> I did drop volume and tried again. Screenshot 2024-02-08 at 10 39 18 AM

maybe try deleting the node_modules folder in /frontend and then doing npm install again?

**Comment by longshuicy** [comment]
> > Something I noticed.
> > I have 2 folders in a dataset. I go to rename the first one.
> > After that, if I click 'rename' on the second one, it shows the name of the first one and not the name of the folder.
> > Uploaded a video.
> > Screen.Recording.2024-02-08.at.9.42.05.AM.mov
> 
> Good catch I'll try fixing it

@tcnichol i think i fixed it. I was over-engineering that part earlier

**Comment by ddey2** [comment]
@longshuicy I git pulled again. Now I can see the 'Rename' option. All is working but I get error after I create a dataset, make a couple of nested folders in it, then change the dataset to 'public' status. When I logged out and come to the publice page, I get error. It might not be related to this PR. Could you check? Else, the code looks good. 
Screenshot 2024-02-08 at 11 13 52 AM
Screenshot 2024-02-08 at 11 14 26 AM

**Comment by longshuicy** [comment]
> @longshuicy I git pulled again. Now I can see the 'Rename' option. All is working but I get error after I create a dataset, make a couple of nested folders in it, then change the dataset to 'public' status. When I logged out and come to the publice page, I get error. It might not be related to this PR. Could you check? Else, the code looks good. Screenshot 2024-02-08 at 11 13 52 AM Screenshot 2024-02-08 at 11 14 26 AM

Todd fixed this issue in another PR already merged. I merged main back. could you check again?

**Review by ddey2 — APPROVED** [review]
All good now.

**Review by tcnichol — APPROVED** [review]
I checked and the bug from before is now fixed, works fine for multiple folders/subfolders. Marking approved.

**Pull request merged**
