### PR TITLE
746 on selecting date time picker widget type doesnt narrow down the field options

### PR DESCRIPTION
**Pull request by longshuicy**
1. Reconstruct the widget type and input type to tie them together
2. Style the form properly
3. Write more typescirpts

image

### CODE REVIEW

**Review by ddey2 — CHANGES_REQUESTED** [review]
It works for the 1st case stated in the bug. I notice 1 more thing while tetsing this.

If you select Dropdown, then list, then selects Date&Time picker, 'supported list value' input box doesn't go away. 
Screenshot 2023-09-27 at 1 34 57 PM
Screenshot 2023-09-27 at 1 35 38 PM

**Comment by tcnichol** [comment]
Tested and I can no longer pick integer or any other types. 

If I pick date I can still pick a time. Is that intended behavior?

**Comment by longshuicy** [comment]
> Tested and I can no longer pick integer or any other types.
> 
> If I pick date I can still pick a time. Is that intended behavior?

Yes that's intended too restrict each widget type with its supported data type

**Review by tcnichol — APPROVED** [review]
Tested this one and marking approved.

**Pull request merged**
