### PR TITLE
fix bug when upload file

### PR DESCRIPTION
**Pull request by longshuicy**
image

The order of parameter of this function changed; so we have to switch the order of `folderId` with `formData`

### CODE REVIEW

**Comment by tcnichol** [comment]
Chen, I am fixing a few things on my branch. I will review this before the end of today.

**Review by tcnichol — APPROVED** [review]
I checked out and tested the branch and it works. I will mark approved.

**Comment by lmarini** [comment]
I am able to upload a new file to a dataset on main. How do I reproduce the bug?

**Comment by longshuicy** [comment]
On main, you do a fresh `npm run codegen:v2:dev` then try upload the file again. You should see it fails @lmarini

**Comment by lmarini** [comment]
A

> On main, if you do a fresh `npm run codegen:v2:dev` then try upload the file again. You should see it fails @lmarini

Thanks, that makes sense

**Review by lmarini — APPROVED** [review]

**Pull request merged**
