### PR TITLE
Build frontend for both linux/amd64 and linux/arm64

### PR DESCRIPTION
**Pull request by lmarini**

### CODE REVIEW

**Comment by KastanDay** [comment]
Testing this on my M1 mac, it seems we need to use a more recent version of `sharp` from npm. 

It appears the Dockerfile tries to install `sharp@0.28.3`. However, shap has only provided native M1 builds since `sharp@0.29.0`. They describe this in their official docs here: https://sharp.pixelplumbing.com/install#apple-m1 

Could we move to a version of sharp >= 0.29.0?

For completeness, here's the full error message:

```
 => ERROR [clowder/clowder2-frontend clowder-build 5/8] RUN npm install                                                                                                                                       53.5s
------
 > [clowder/clowder2-frontend clowder-build 5/8] RUN npm install:
#0 0.414 npm WARN lifecycle clowder-frontend@0.1.0~preinstall: cannot run in wd clowder-frontend@0.1.0 node tools/nodeVersionCheck.js (wd=/usr/src/app)
#0 51.85
#0 51.85 > sharp@0.28.3 install /usr/src/app/node_modules/sharp
#0 51.85 > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
#0 51.85
#0 51.93 sharp: Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.10.6
#0 51.93 sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
#0 52.64 npm WARN clowder-frontend@0.1.0 No description
#0 52.65 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
#0 52.65 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#0 52.66 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
#0 52.66 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#0 52.67 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
#0 52.67 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
#0 52.67
#0 52.68 npm ERR! code ELIFECYCLE
#0 52.68 npm ERR! errno 1
#0 52.69 npm ERR! sharp@0.28.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`
#0 52.69 npm ERR! Exit status 1
#0 52.69 npm ERR!
#0 52.69 npm ERR! Failed at the sharp@0.28.3 install script.
#0 52.69 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#0 52.70
#0 52.70 npm ERR! A complete log of this run can be found in:
#0 52.70 npm ERR!     /root/.npm/_logs/2022-07-08T17_14_40_702Z-debug.log
------
failed to solve: executor failed running [/bin/sh -c npm install]: exit code: 1
```

**Comment by KastanDay** [comment]
I talked with @longshuicy and she said we're not using `favicons`, so for now removing `favicons` and its dependency `sharp` should make the build work. 

I'm pretty sure favicons depends on `sharp 0.28.3` which is incompatible with M1.

**Comment by KastanDay** [comment]
The build succeeded, I think this is safe to merge! 

Down the line, we should probably use a different npm package for favicon support.

**Comment by longshuicy** [comment]
Looking at INCORE frontend. I'm not using favicon library. 
I think just HtmlWebpackPlugin should work:
```
new HtmlWebpackPlugin({
    favicon: "./src/public/favicon.ico"
})
```

**Review by longshuicy — APPROVED** [review]

**Comment by lmarini** [comment]
Thanks @KastanDay @longshuicy !

**Pull request merged**
