### PR TITLE
update file content model

### PR DESCRIPTION
**Pull request by longshuicy**
Now the content type is not a simple string instead an object that has two fields. 
Update all the codegen models as well to reflect that.

To test:

Just open any datasets that has file in it.

### CODE REVIEW

**Comment by tcnichol** [comment]
@longshuicy I checked this one and it fixes the bug. Could someone review this and get it merged in?

**Comment by tcnichol** [comment]
Ran into an issue:

When I try to submit a file to an extractor, I get the blank page again. Will get a bit and post more comments.

**Comment by tcnichol** [comment]
@longshuicy 
I was testing so I pushed 2 small changes. A method somehow got removed from the FilesService for extraction, and posting metadata also caused the blank page.

**Comment by longshuicy** [comment]
> @longshuicy I was testing so I pushed 2 small changes. A method somehow got removed from the FilesService for extraction, and posting metadata also caused the blank page.

Looks good to me. I can't approve cuz it's my branch :-p. But you can approve

**Review by max-zilla — APPROVED** [review]

**Pull request merged**
