### PR TITLE
fix extractor error beanie branch

### PR DESCRIPTION
**Pull request by tcnichol**
Like main, the dataset_id and folder_id need to be str and not objectid

### CODE REVIEW

**Review by ddey2 — CHANGES_REQUESTED** [review]
Doesn't work still. shows backend failure.

TypeError: 'DatasetDB' object is not subscriptable

**Comment by ddey2** [comment]
Screenshot 2023-06-05 at 3 13 44 PM

**Comment by tcnichol** [comment]
I will clear my db and check again on this.

**Comment by lmarini** [comment]
@tcnichol said this might have started on the wrong branch. He will take a second look.

**Comment by max-zilla** [comment]
I believe this particular bug (and some associated ones) are fixed in my PR here: https://github.com/clowder-framework/clowder2/pull/534
we can merge this first or just close it if you prefer.

**Pull request closed without merging**
