### PR TITLE
Backend now pickups JWT token in cookie left by frontend and

### PR DESCRIPTION
**Pull request by lmarini**
uses it to authenticate users. This should let us open a download window for files and datasets that will not run out of memory unlike the download in javascript approach.

### CODE REVIEW

**Comment by tcnichol** [comment]
I'm having an issue uploading a large file on this branch. It's a 39 GB zip archive. I see this:
upload_error

**Comment by ddey2** [comment]
I tried with 1.5GB file. It works fine, within few seconds. I couldn't see a separate tab opened when I downloaded the file.

**Comment by longshuicy** [comment]
@tcnichol @ddey2 The frontend still need to change how upload/download works to address the large file issue. I will address them in another PR. This PR provides the backend support for the change.

**Comment by longshuicy** [comment]
Everything should work with download now

**Pull request merged**
