### PR TITLE
929 message on empty page if there is no datasets

### PR DESCRIPTION
**Pull request by tcnichol**
This is a draft pull request. I don't think it looks very good visually, but it adds a message and a button to register or login on the public page if there are no public datasets.

### CODE REVIEW

**Comment by ddey2** [comment]
I think the login and register button are not needed. We laready have them on top right of the page. Just a message for now is good, I think.

**Comment by tcnichol** [comment]
> I think the login and register button are not needed. We already have them on top right of the page. Just a message for now is good, I think.

I removed them. 

It might be a good idea to maybe have a place where, for each instance, an admin can set a default message. But that would probably be another issue. There was something like this in clowder v1 I recall.

**Comment by ddey2** [comment]
I think this is good for now. We may want to go for a landing page in future. That can be a separate issue.

**Comment by longshuicy** [comment]
For some reason i got 404 error access public_dataset endpoint
image

**Comment by lmarini** [comment]
Please make it against beta.2

**Review by longshuicy — APPROVED** [review]

**Pull request merged**
