### PR TITLE
Private extractor support

### PR DESCRIPTION
**Pull request by max-zilla**
Adds optional support for an owner in the extractor heartbeat. 

To test this, run an extractor with the following ENV VARs:

```
export CLOWDER_EMAIL=mburnet2@illinois.edu
export EXTRACTOR_KEY=secret_test
```

When the extractor starts, the email will be assigned as owner. That user should be able to see the extractor in lists as normal, but other users cannot. There are endpoints to grant other permissions:

```
POST/DELETE http://localhost:8000/api/v2/listeners/123/users/fake@email.com
POST/DELETE http://localhost:8000/api/v2/listeners/123/groups/456
POST/DELETE http://localhost:8000/api/v2/listeners/123/datasets/456
```
...where 123 is extractor ID, and 456 is group ID. Only owner has permission to do this currently.

BASIC RULES.

If you are looking at a file or dataset Analysis tab, you will see extractor listed...
- if extractor's access field is null
- if you are access.owner, listed in access.users, or in a group listed in access.groups
- if the dataset or the file's dataset are listed in access.datasets

If you are looking at Extraction History, same rules but dataset rule is ignored. NOTE: if the user has submitted a job to an extractor, they should be able to see it here... need to work out permissions on that.

Changed the logic slightly for the process filter so if the extractor has process set to {} for file or dataset (i.e. no rule specified) it will be included in those lists.

### CODE REVIEW

**Comment by tcnichol** [comment]
I'm running this but getting an error in the heartbeat:

```
    raise exc
  File "/Users/helium/ncsa/clowder2/backend/heartbeat_listener.py", line 34, in callback
    owner = msg["owner"]
KeyError: 'owner'
```

I checked in the extractor I am running and the environment variables are set. 

Do I need a specific version of pyclowder? Here's my environment variables as I've set th
Screenshot 2024-05-02 at 11 55 37 AM
em.

**Review by tcnichol — APPROVED** [review]
Tested this with the corresponding pyclowder branch. Private extractor registers, only visible to the user.

**Comment by lmarini** [comment]
Does the pyclowder branch need to be merged before this one?

**Comment by lmarini** [comment]
Sorry can you resolve conflicts, thanks!

**Review by lmarini — CHANGES_REQUESTED** [review]
There might be an issue. I added some extractors with this branch running. I enabled them.  When I go to the dataset page and click on the Analysis tab I get a blank page and errors in backend and frontend. Guessing it's not able to serialize the something in the new extractor json.

> INFO:     127.0.0.1:65327 - "GET /api/v2/listeners?skip=0&limit=5&heartbeat_interval=0&category=&label=&alive_only=false&process=dataset&all=665df0aa6cdde48fda0fde9e&dataset_id=false HTTP/1.1" 422 Unprocessable Entity

> Uncaught Error: Objects are not valid as a React child (found: object with keys {loc, msg, type}). If you meant to render a collection of children, use an array instead.
    React 16
    unstable_runWithPriority scheduler.development.js:468
    React 4
    Redux 4
    s (index):3
    middleware Redux
    immutableStateInvariantMiddleware Immutable
    dispatch Redux
    fetchListenerCategories listeners.js:147
    promise callback*then CancelablePromise.ts:81
    fetchListenerCategories listeners.js:146
    middleware Redux
    immutableStateInvariantMiddleware Immutable
    dispatch (index):6
    listAvailableCategories Listeners.tsx:72
    Listeners Listeners.tsx:101
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 4
    unstable_runWithPriority scheduler.development.js:468
    React 17
    tsx index.tsx:14
    Webpack 3
[react-dom.development.js:13231](webpack://clowder-frontend/node_modules/react-dom/cjs/react-dom.development.js)
The above error occurred in the <p> component:

p
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
Typography@http://localhost:3000/main.bundle.js:70947:87
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
DialogContentText@http://localhost:3000/main.bundle.js:49627:83
div
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
DialogContent@http://localhost:3000/main.bundle.js:49498:82
div
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
Paper@http://localhost:3000/main.bundle.js:60706:83
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
div
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
Transition@http://localhost:3000/main.bundle.js:238854:30
Fade@http://localhost:3000/main.bundle.js:50560:77
FocusTrap@http://localhost:3000/main.bundle.js:37082:7
div
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
Portal@http://localhost:3000/main.bundle.js:37815:7
Modal@http://localhost:3000/main.bundle.js:58736:82
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
Dialog@http://localhost:3000/main.bundle.js:48993:83
ActionModal@http://localhost:3000/main.bundle.js:124340:20
ErrorModal@http://localhost:3000/main.bundle.js:124383:19
main
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
div
./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js/withEmotionCache/<@http://localhost:3000/main.bundle.js:13186:66
Box@http://localhost:3000/main.bundle.js:78283:72
PersistentDrawerLeft@http://localhost:3000/main.bundle.js:119552:74
Dataset@http://localhost:3000/main.bundle.js:121627:80
PrivateRoute@http://localhost:3000/main.bundle.js:151156:18
RenderedRoute@http://localhost:3000/main.bundle.js:237340:7
Routes@http://localhost:3000/main.bundle.js:238029:7
Router@http://localhost:3000/main.bundle.js:237968:7
BrowserRouter@http://localhost:3000/main.bundle.js:235921:7
AppRoutes
Provider@http://localhost:3000/main.bundle.js:233513:15
RtlProvider@http://localhost:3000/main.bundle.js:77228:9
ThemeProvider@http://localhost:3000/main.bundle.js:74294:7
ThemeProvider@http://localhost:3000/main.bundle.js:77517:7
ThemeProvider@http://localhost:3000/main.bundle.js:72567:9

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. [localhost:3000:12714:25](http://localhost:3000/)

​

**Comment by lmarini** [comment]
I think the issue above is also reflected in the failing pytest:

> FAILED app/tests/test_feeds.py::test_feeds - assert 422 == 200
>  +  where 422 = <Response [422 Unprocessable Entity]>.status_code

**Comment by max-zilla** [comment]
> I think the issue above is also reflected in the failing pytest:
> 
> > FAILED app/tests/test_feeds.py::test_feeds - assert 422 == 200
> > 
> > * where 422 = <Response [422 Unprocessable Entity]>.status_code

This should be resolved. It was due to the ListenerAuthorization dependency injection I added using `listener_id` in most places, but in this particular call we are POSTing a small object with listener_id and `automatic` so the validation was failing. I separated the call to ListenerAuthorization outside of dependency on this call only, for lack of a better idea

**Comment by ddey2** [comment]
Something is not quite right here. On Extractor page, users should be able to see all the extractors(probably not the private extractor) irrespective of admin mode.

Here on this branch, I can see them in admin mode. When I click on 'Drop admin mode', the page doesn't refresh on it's own. After explicitly refreshing the page, it shows empty list.
Screenshot 2024-06-24 at 2 02 54 PM
Screenshot 2024-06-24 at 2 03 10 PM

**Comment by tcnichol** [comment]
@max-zilla 
I am seeing this error

`INFO:     127.0.0.1:54745 - "GET /api/v2/listeners?skip=0&limit=5&heartbeat_interval=0&category=&label=&alive_only=false&dataset_id=true&all=false&enable_admin=false HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/helium/ncsa/clowder2/backend/app/routers/listeners.py", line 437, in get_listeners
    EventListenerDB.access.datasets == PydanticObjectId(dataset_id),
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/bson/objectid.py", line 103, in __init__
    self.__validate(oid)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/bson/objectid.py", line 201, in __validate
    _raise_invalid_id(oid)
  File "/Users/helium/.virtualenvs/backend-qaHHe5b_/lib/python3.9/site-packages/bson/objectid.py", line 35, in _raise_invalid_id
    raise InvalidId(
bson.errors.InvalidId: 'true' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string`

**Comment by tcnichol** [comment]
@max-zilla I see that error when I am on the page and am not in superAdmin mode. And no extractors are visible at all until I reload the page with superAdmin.

I was thinking that they should show up, and we just need superAdmin mode to enable/disable?

**Comment by tcnichol** [comment]
I think I fixed the error that was causing no extractors to be visible. The component was sending in 'true' as a dataset_id as a default value. It should be 'null' and then the next one for 'all' should be 'true.' Committed this.

**Comment by tcnichol** [comment]
> Something is not quite right here. On Extractor page, users should be able to see all the extractors(probably not the private extractor) irrespective of admin mode.
> 
> Here on this branch, I can see them in admin mode.
> 
> 1. When I click on 'Drop admin mode', the page doesn't refresh on it's own.
> 2. After explicitly refreshing the page, it shows empty list.
> 
> Screenshot 2024-06-24 at 2 02 54 PM Screenshot 2024-06-24 at 2 03 10 PM 3. When I am a diff regular user (other than the owner of private extractor), I can see no extracator.
> I think all these might be related to the ListnerAuth class.

This might be fixed by the commit I made. 
I would like someone else to check that it is working as intended.
 See comment at end.

**Comment by tcnichol** [comment]
With the commit I made, I think things work as intended for the admin user, but I don't think it is working for other users.

I registered the wordcount extractor NOT as a private one, and even if it's running and enabled, it still only shows up for my admin user, and not for any others.

**Comment by tcnichol** [comment]
I found what was going wrong here. 

When extractors are picked up by the heartbeat, the owner is "" but the script checks if they are None. I added that and now extractors that are not private are showing up like they should. 

I did create an issue and a branch, but since this is such a tiny fix I just put it here. 

To test, kill the heartbeat_listener docker container, and run the script in pycharm. Access will be None for public extractors registered.

**Comment by max-zilla** [comment]
thanks for the fix, @tcnichol !

**Review by lmarini — APPROVED** [review]

**Pull request merged**
